import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  scrollViewContainer: {
    flexGrow: 1,
  },
  container: {
    flex: 1,
    padding: 7,
    backgroundColor: '#fff',
  },
  title: {
    fontSize: 20,
    textAlign: 'center',
    fontWeight: 'bold',
    marginBottom: 16,
    color: "#fff",
  },
  inputContainer: {
    width: "100%",
    flex: 1,
    padding: 15,
    backgroundColor: "#192a57",
    borderRadius: 15,
    overflow: "hidden",
  },
  input: {
    height: 40,
    borderColor: "gray",
    borderWidth: 3,
    marginBottom: 12,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "#fff",
    color: "#000",
  },
  acordion: {
    height: 55,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    color: "#000",
  },
  item:{
    backgroundColor: "#fff",
    color: "#000",
  },
  inputAcordion: {
    height: 40,
    borderColor: "gray",
    borderWidth: 3,
    marginTop:3,
    marginBottom: 12,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "#fff",
    color: "#000",
  },
  buttonContainer: {
    marginTop: 3,
    width: "100%",
    flex: 1,
    padding: 15,
    backgroundColor: "#303b4e",
    borderRadius: 15,
    overflow: "hidden",
  },
  buttonSalvar: {
    marginTop: 10,
    height: 40,
    backgroundColor: "#0078d4",
    borderColor: "gray",
    borderWidth: 2,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  buttonDetalle: {
    marginTop: 10,
    height: 40,
    backgroundColor: "#07EB06",
    borderColor: "gray",
    borderWidth: 2,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  findButton: {
    width: 50,
    backgroundColor: '#0078d4',
    padding: 10,
    alignItems: 'center',
    borderRadius: 5,
    marginBottom: 12,
  },
  deleteButton: {
    width: 50,
    backgroundColor: 'red',
    padding: 10,
    alignItems: 'center',
    borderRadius: 5,
    marginBottom: 12,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
});
